### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'X.pickle'

### ISSUE THREAD

**Issue by esmaykel** [ParanoidAndroid19/Car-Damage-Analysis#1]
Hello, 
When I try to run loaded_data.py python script I have the error: FileNotFoundError: [Errno 2] No such file or directory: 'X.pickle'.
Can you help me, please?

**Comment by ParanoidAndroid19** [comment]
I forgot to add those files, I have added them now.

**Comment by esmaykel** [comment]
Thanks you!!!

**Comment by esmaykel** [comment]
By the way, you forgot to remove the character <'> from X1 = pickle.load(open("X'.pickle", "rb"))
Y1 = pickle.load(open("Y'.pickle", "rb"))
;-)
